---
## configuration directory
config_dir: /opt/katana

## ToS configuration
## https://en.wikipedia.org/wiki/Type_of_service
tos: false
tcp_tos: "0x00"
udp_tos: "0x00"

## qdisc configuration
fq_codel: "fq_codel target 1000us interval 2000us noecn limit 2048 flows 1024 quantum 300"
_txqueuelen: 64

## supported qdisc: noqueue, fq_codel
qdisc: fq_codel

