---
## katana configuration directory
config_dir: /opt/katana

## package list for installation
packages:
- vim
- bash-completion
- curl
- ca-certificates
- net-tools
- dnsutils
- tcpdump
- ethtool

## sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: "{{ ansible_host }}"
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

## name servers
dns: 1.1.1.1
dns_fallback: 1.0.0.1
dns_v6: 2606:4700:4700::1111
dns_v6_fallback: 2606:4700:4700::1001

## enable IPv6 name servers
enable_ipv6_dns: false

## limits configuration
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000
