---
- name: Disable and stop unnecessary services
  shell: |
    set -e

    SERVICES=(
      apparmor systemd-resolved rsyslog logrotate auditd
      acpid acpid.path acpid.socket
      cloud-config cloud-final cloud-init-local cloud-init cloud-init-hotplugd.socket
      e2scrub_reap e2scrub_all.timer
      open-iscsi iscsid.socket
      qemu-guest-agent ssh-keygen
      systemd-pstore tuned
      apt-daily.timer apt-daily-upgrade.timer dpkg-db-backup.timer fstrim.timer
      remote-fs.target
    )

    for svc in "${SERVICES[@]}"; do
      systemctl stop "$svc" 2>/dev/null || true
      systemctl disable "$svc" 2>/dev/null || true
      systemctl mask "$svc" 2>/dev/null || true
    done
  args:
    executable: /bin/bash
  async: 120
  poll: 0
  ignore_errors: true

- name: Make limits.conf
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    mode: 0644
    owner: root
    group: root

- name: Make coredump.conf
  template:
    src: coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    mode: 0644
    owner: root
    group: root

- name: Disable journald logging
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#Storage='
    line: 'Storage=none'
    state: present
  ignore_errors: true  

