---
- name: Set GRUB parameters
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*'
    replace: |
      GRUB_CMDLINE_LINUX_DEFAULT="loglevel=0 printk.devkmsg=off quiet audit=0 mitigations=off nohalt pti=off schedstats=off nohz=on {% if ansible_processor_vcpus|int > 1 %}nohz_full=1-{{ ansible_processor_vcpus - 1 }} rcu_nocbs=1-{{ ansible_processor_vcpus - 1 }} irqaffinity=0-{{ ansible_processor_vcpus - 1 }}{% endif %} nosoftlockup nokprobes nokaslr perf_event_paranoid=3 transparent_hugepage=never threadirqs highres=on rcupdate.rcu_expedited=1"

- name: Update GRUB configuration
  command: update-grub

- name: Reboot the system
  reboot:
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 5
