---
- name: Map ansible_architecture to RT kernel arch
  set_fact:
    kernel_arch_map:
      x86_64: amd64
      aarch64: arm64

- name: Install real-time kernel
  apt:
    name: "linux-image-rt-{{ kernel_arch_map[ansible_architecture] | default(ansible_architecture) }}"
    state: present
    update_cache: true

